from rsf.proj import *

par = {
    'nt': 601,
    'nz': 401,
    'nx': 401,
    'nm': 20,
    'igz': 2,
    'igxb': 101,
    'igxe': 301,
    'isz': 3,
    'isxb': 200,
    'isxe': 200,
    'isxd': 20,
    'dz': 0.01,
    'dx': 0.01,
    'dt': 0.004,
    'fpeak': 5
    }

def Movie(title):
    Plot(title,'grey gainpanel=all wanttitle=n',view=1)
    Alias('movies',title+'.vpl')

def modmig(par):
    # Layered model
    Flow('layermodel',None,'vam nz=%(nz)d nx=%(nx)d dz=%(dz)g dx=%(dx)g' % par)
    Result('layermodel',
           '''
           grey color=j allpos=y bias=1.5
           scalebar=y wanttitle=n barreverse=y
           ''')

    wave = '''
    nt=%(nt)d dt=%(dt)g isz=%(isz)d
    isxbeg=%(isxb)d isxend=%(isxe)d iskip=%(isxd)d
    igz=%(igz)d igxbeg=%(igxb)d igxend=%(igxe)d
    fpeak=%(fpeak)g source=${TARGETS[1]} nm=%(nm)d
    ''' % par

    # Variable velocity
    Flow('trace wave','layermodel','wave ' + wave)
    if par['nm'] != 0:
        #Movie('wave')
        Result('wave','grey gainpanel=all wanttitle=n')

    Result('trace','grey title=Data')

    # Constant velocity
    Flow('hom','layermodel','math output=1.5')
    Flow('tracehom wavehom','hom','wave ' + wave)
    #if par['nm'] != 0:
        #Movie('wavehom')
    Result('tracehom','grey title="Data (Homogeneous Model)"')

    # Difference
    Flow('tracediff','trace tracehom','add scale=1,-1 ${SOURCES[1]}')
    Result('tracediff','grey title="Data (Reflection)"')
    Plot('trace','grey title="trace"')
    Plot('tracehom','grey title="trace hom"')
    Plot('tracediff','grey title="diff"')
    Result('traces','trace tracehom tracediff','SideBySideAniso')

    # Reverse-time migration
    rtm = '''
    ../rtm trace=${SOURCES[1]}
    isz=%(isz)d isxbeg=%(isxb)d isxend=%(isxe)d iskip=%(isxd)d
    igz=%(igz)d igxbeg=%(igxb)d igxend=%(igxe)d --readwrite=y
    ''' % par

    # Flow('source','hom tracediff',rtm + ' source=$TARGET',stdout=0)

    Flow('rtm ','hom tracediff ', rtm)

    Result('rtm','grey title=Image')

modmig(par)

End()
