/* This file is automatically generated. DO NOT EDIT! */

#ifndef _step_h
#define _step_h


void step_forward(float * tgt_p, 
		  float * src_p, 
		  float * v,
		  int nz, int nx,
		  float rz, float rx, float s);
/*< step forward >*/

#endif
