/* This file is automatically generated. DO NOT EDIT! */

#ifndef _wavefun_h
#define _wavefun_h


typedef struct {
    int nz;          /* number of gridpoints in z */
    int nx;          /* number of gridpoints in x */
    int nt;          /* number of time steps */
    int nm;          /* number of time steps to skip between movie frames
			(<=0 for no movie) */
    float dz;        /* step in z */
    float dx;        /* step in x */
    float dt;        /* step in t */
    float freq;      /* center frequency of Ricker wavelet */
    int isz;         /* source depth, in units of dz */
    int isxbeg;      /* far left source x coord in units of dx */
    int isxend;      /* far right source x coord in units of dx */
    int iskip;       /* interval between sources in units of dx */
    int igz;         /* recvr depth, in units of dz */
    int igxbeg;      /* far left receiver x coord in units of dx */
    int igxend;      /* far right receiver x coord in units of dx */
    int imbeg;       /* midpoint begin */
    int imend;       /* midpoint end */
    int imskip;      /* midpoint skip */
    int ihmax;       /* offset radius, units of dx */
    sf_file vfile;    /* velocity file - defines space grid */
    sf_file tfile;    /* trace output file */
    sf_file mfile;    /* movie file */
    sf_file rmfile;   /* receiver movie file */
    sf_file imfile;   /* image file */
} WINFO;


void getinputs(bool mod,  /* modeling or migration */ 
	       WINFO * wi /* parameters */);
/*< get input parameters >*/


void fassign(float * a, float c, int n);
/*< assign constant to array - presumes memory already allocated >*/


void fzeros(float * a, int n);
/*< assign zero to array - presumes memory already allocated >*/


void fsquare(float * a, int n);
/*< square array elements - presumes memory already allocated
  and initialized >*/


float fgetmax(float * a, int n);
/*< get max val from array >*/


float fgetmin(float * a, int n);
/*< get min val from array >*/


float fgetrick(float t, float fpeak);
/*< return value at t of causal Ricker wavelet with peak frequency f >*/

#endif
